config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :questions do
    collection do
      get :unsolved
      get :solved
    end
    resources :answers, only: [:create]
  end
  root to: 'questions#index'
  
  namespace :admin do
    root to: 'questions#index'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :users
    resources :questions, only: [:index, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true

  belongs_to :user
  has_many :answers, dependent: :destroy
  #質問が削除された場合紐付く回答も削除される
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :require_admin
  
  
  
  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(10)
  end
  
  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
    redirect_to questions_url, notice: "質問を「#{@question.title}」削除しました。"
  end
  
  private
  def require_admin
    if current_user.nil? || !current_user.admin?
      redirect_to root_path, notice: '管理者ではありません'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user, {only:[:new, :create, :edit, :update, :destroy]}
  #ログインしているのかを確かめる
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}
  # 質問の編集ができるのは、質問投稿した人のみ
  before_action :set_question, {only:[:show, :edit, :update, :destroy]}
  # 共通部分
  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def new
    @question = Question.new
  end
  
  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      User.all.each do |user|
        next if user == current_user
        QuestionMailer.with(user: user, question: @question).creation_question.deliver_later
        # 新規質問が投稿されたら全ユーザーにメールを送信する
      end
      redirect_to questions_url, notice: "質問を「#{@question.title}」投稿しました。"
    else
      render :new
    end
  end

  def show
    @answer = Answer.new
  end

  def edit
  end
  
  def update
    @question.update!(question_params)
    redirect_to questions_url, notice: "質問を「#{@question.title}」更新しました。"
  end
  
  def destroy
    @question.destroy!
    redirect_to questions_url, notice: "質問を「#{@question.title}」削除しました。"
  end
  
  def solved
    @q = Question.where(status: 0).ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(10)
    render :action => 'index'
  end
  
  def unsolved
    @q = Question.where(status: 1).ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page]).per(10)
    render :action => 'index'
  end
  
  private
  
  def question_params
    params.require(:question).permit(:title, :body, :status)
  end
  
  def ensure_correct_user
    @question = Question.find_by(id: params[:id])
    if @question.user_id != current_user.id
      redirect_to root_url, notice: "権限がありません"
    end
  end
  
  def set_question
    @question = Question.find(params[:id])
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
- if question.errors.present?
  ul#error_explanation
    - question.errors.full_messages.each do |message|
      li= message

= form_with model: question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'question_title'
  .form-group
    = f.label :body
    = f.text_area :body, rows: 5, class: 'form-control', id: 'question_body'
  = f.submit nil, class: 'btn btn-primary'

app/views/questions/edit.html.slim
h1 質問の編集


- if @question.errors.present?
  ul#error_explanation
    - question.errors.full_messages.each do |message|
      li= message

.nav.justify-content-end
  = link_to '一覧', questions_path, class: 'btn btn-primary'

= form_with model: @question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'question_title'
  .form-group
    = f.label :body
    = f.text_area :body, rows: 5, class: 'form-control', id: 'question_body'
  .form-group
    =f.label :status
    = f.select :status, [['未解決',0],['解決',1]], {}, class: 'form-control', id: 'question_status'
  = f.submit nil, class: 'btn btn-primary'

app/views/questions/index.html.slim
h1 質問一覧

= link_to '新規質問', new_question_path, class: 'btn btn-primary'

= link_to 'すべて', questions_path, class: 'btn btn-outline-primary btn-sm ml-2'
= link_to '未解決', solved_questions_path, class: 'btn btn-outline-primary btn-sm ml-1'
= link_to '解決済み', unsolved_questions_path, class: 'btn btn-outline-primary btn-sm ml-1'
  

= search_form_for @q, class: 'my-5' do |f| 
  .form-group.row
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control', placeholder: '検索ワード'
    .col-sm-2
      = f.submit class: ' btn btn-outline-primary'

   

.mb-3
table.table.table-hover
  tbody
    - @questions.each do |question|
      tr
        td= link_to "/users/#{question.user.id}"
          - if question.user.avatar?
            = image_tag question.user.avatar.url, :class => 'rounded-circle', :size =>'32x32'
          - else
            = image_tag 'icons8-male-user-90', :class => 'rounded-circle', :size =>'32x32'
        td= link_to question.title, question
     

.mb-3
  = paginate @questions

app/views/questions/new.html.slim
h1 新規質問
  
- if @question.errors.present?
  ul#error_explanation
    - question.errors.full_messages.each do |message|
      li= message

.nav.justify-content-end
  = link_to '一覧', questions_path, class: 'btn btn-primary'

= form_with model: @question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'question_title'
  .form-group
    = f.label :body
    = f.text_area :body, rows: 5, class: 'form-control', id: 'question_body'
  .form-group
    =f.hidden_field :status,:value => 0, id: 'question_status'
  = f.submit nil, class: 'btn btn-primary'

app/views/questions/show.html.slim
h1 質問詳細

.nav.justify-content-end
- if @current_user.present? && @question.user_id == @current_user.id
  = link_to '削除', @question, method: :delete, data: { confirm: "質問「#{@question.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger float-right'
  = link_to '編集', edit_question_path, class: 'btn btn-primary mr-1 float-right'
/ @current_user.present?を記述することで、ユーザーがログインしていない場合は、このif文自体全部をスキップさせる
table.table.table-hover
  tbody
    tr
      th= Question.human_attribute_name(:title)
      td= @question.title
    tr
      th= Question.human_attribute_name(:body)
      td= simple_format(h(@question.body), {}, sanitize: false, wrapper_tag: "div")

= form_with model: [@question, @answer], local: true do |f|
  .form-group
    = f.label :body
    = f.text_area :body, rows: 5, class: 'form-control', id: 'answer_body'
  = f.submit '回答する', class: 'btn btn-primary'
  
.mb-3
table.table.table-hover
  tbody
    - @question.answers.each do |answer|
      tr
        td= link_to "/users/#{answer.user.id}"
          - if answer.user.avatar?
            = image_tag answer.user.avatar.url, :class => 'rounded-circle', :size =>'32x32' 
          - else
            = image_tag 'icons8-male-user-90', :class => 'rounded-circle', :size =>'32x32'
        td= answer.body
        