config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :questions do
    collection do
      get :unsolved
      get :solved
    end
    resources :answers, only: [:create]
  end
  root to: 'questions#index'
  
  namespace :admin do
    root to: 'questions#index'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :users
    resources :questions, only: [:index, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Qanda
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-li
      .navbar-brand QandA
      ul.navbar-nav.ml-auto
        - if @current_user
          - if @current_user.admin?
            li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
            li.nav-item= link_to '質問一覧', admin_questions_path, class: 'nav-link'
            li.nav-item= link_to '管理者作成', new_admin_user_path, class: 'nav-link'
          - else
            li.nav-item= link_to '質問一覧', root_path, class: 'nav-link'
            li.nav-item= link_to 'ユーザー一覧', users_path, class: 'nav-link'
          li.nav-item= link_to "/users/#{@current_user.id}"
                       = image_tag 'icons8-customer-100', :class => 'rounded-circle', :size =>'30x30' 
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to '新規登録', new_user_path, class: 'nav-link'
          li.nav-item= link_to '質問一覧', root_path, class: 'nav-link'
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield